<?php
/**
 * @var \Martinkuhl\AutheliaOidc\Block\Adminhtml\Login\Button $block
 */
if ($block->isEnabled()):
?>
<div class="authelia-oidc-button-container">
    <a class="action-default scalable authelia-oidc-button" href="<?= $block->getRedirectUrl() ?>">
        <span>Login mit Authelia</span>
    </a>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "autheliaButtonFix": {}
    }
}
</script>
<?php endif; ?>
